apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection-container
        image: meharsazan1/new
        ports:
        - containerPort: 8000
